"""Build the evaluation corpus (test-plan §4).

Every sample is *built, not collected*. That is the whole design: ground truth
falls out of the build instead of out of someone's reverse engineering, and
nothing in `corpus/` is redistributed from anyone else.

    python -m corpus.build            # everything
    python -m corpus.build --only cng # just the sources whose name contains it

Needs `zig cc` and nothing else. Zig cross-compiles to both Windows targets from
any host, which is what lets the corpus build identically on a Linux CI runner
and on the author's Windows laptop - a corpus that only builds in one place is
a corpus nobody re-runs.
"""

import argparse
import os
import random
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "src"
MATERIAL = ROOT / "material"
BUILD = ROOT / "build"

TARGETS = {"x86": "x86-windows-gnu", "x64": "x86_64-windows-gnu"}
"""Both architectures, because import thunk layout and constant alignment
differ between them and a signature that works on one is not proven on both."""

OPT_LEVELS = {"O0": "-O0", "O2": "-O2"}
"""-O0 and -O2 only. -O1 and -Os move nothing that matters here, and every extra
level doubles the corpus for no new measurement."""

LIBS = ["-lbcrypt", "-ladvapi32"]
"""Passed to every sample. The linker drops what is unreferenced, so a sample
that never calls CNG does not gain a bcrypt.dll import from this - which the
negative samples' expected results depend on, and which the eval would catch
immediately if it were false."""

NOISE_SEED = 20260826
"""Fixed, so negative_entropy_blob is byte-identical between builds."""


def find_zig(explicit: str | None) -> str:
    """Locate `zig`. Ordinary PATH lookup first, then the place winget puts it.

    The winget fallback exists because `winget install zig.zig` does not put zig
    on PATH until the shell is restarted, and losing an afternoon to that is a
    poor introduction to the project.
    """
    if explicit:
        return explicit
    found = shutil.which("zig")
    if found:
        return found
    packages = Path(os.environ.get("LOCALAPPDATA", "")) / "Microsoft" / "WinGet" / "Packages"
    for candidate in sorted(packages.glob("zig.zig_*/zig-*/zig.exe"), reverse=True):
        return str(candidate)
    raise SystemExit(
        "zig not found. Install it (winget install zig.zig, or your package\n"
        "manager, or https://ziglang.org/download/) and re-run, or pass --zig PATH."
    )


def c_array(name: str, data: bytes) -> str:
    """Emit `static const unsigned char NAME[] = {...};`.

    Generated rather than committed so the blobs have exactly one source of
    truth: the files in corpus/material. A hand-transcribed copy would drift the
    first time anyone regenerated the key.
    """
    rows = []
    for start in range(0, len(data), 16):
        rows.append("    " + ",".join(f"0x{byte:02x}" for byte in data[start : start + 16]) + ",")
    body = "\n".join(rows)
    return f"static const unsigned char {name}[] = {{\n{body}\n}};\n"


def write_headers(build_dir: Path) -> None:
    """Generate the headers the embedded-material and entropy samples include."""
    blobs = {
        "CORPUS_CERT_PEM": (MATERIAL / "cert.pem").read_bytes(),
        "CORPUS_CERT_DER": (MATERIAL / "cert.der").read_bytes(),
        "CORPUS_KEY_PKCS8_PEM": (MATERIAL / "key.pem").read_bytes(),
        "CORPUS_KEY_PKCS1_PEM": (MATERIAL / "rsa-key.pem").read_bytes(),
        "CORPUS_KEY_PKCS1_DER": (MATERIAL / "rsa-key.der").read_bytes(),
    }
    header = (
        "/* Generated by corpus/build.py from corpus/material/. Do not edit. */\n"
        "#ifndef CORPUS_MATERIAL_BLOBS_H\n#define CORPUS_MATERIAL_BLOBS_H\n\n"
        + "\n".join(c_array(name, data) for name, data in blobs.items())
        + "\n#endif\n"
    )
    (build_dir / "material_blobs.h").write_text(header)

    # 4 KB of uniform noise: the entropy heuristic's designed-in false positive,
    # made reproducible so the count in the eval report is stable.
    rng = random.Random(NOISE_SEED)
    noise = bytes(rng.randrange(256) for _ in range(4096))
    (build_dir / "noise_blob.h").write_text(
        "/* Generated by corpus/build.py. Not a key - see negative_entropy_blob.c. */\n"
        "#ifndef CORPUS_NOISE_BLOB_H\n#define CORPUS_NOISE_BLOB_H\n\n"
        + c_array("CORPUS_NOISE", noise)
        + "\n#endif\n"
    )

    # A 32-byte symmetric key, drawn rather than chosen. Hand-picking the bytes
    # would quietly decide the entropy heuristic's recall in advance: the
    # threshold is 30 distinct bytes out of 32, and a random key lands at about
    # 30. A key someone types out tends to land at 32.
    key = bytes(rng.randrange(256) for _ in range(32))
    (build_dir / "raw_key.h").write_text(
        f"/* Generated by corpus/build.py. {len(set(key))} distinct bytes of 32. */\n"
        "#ifndef CORPUS_RAW_KEY_H\n#define CORPUS_RAW_KEY_H\n\n"
        + c_array("CORPUS_RAW_KEY", key)
        + "\n#endif\n"
    )


def compile_one(zig: str, source: Path, arch: str, opt: str, build_dir: Path) -> Path | None:
    output = build_dir / f"{source.stem}-{arch}-{opt}.exe"
    command = [
        zig,
        "cc",
        "-target",
        TARGETS[arch],
        OPT_LEVELS[opt],
        f"-I{build_dir}",
        f"-I{SRC}",
        "-o",
        str(output),
        str(source),
        *LIBS,
    ]
    result = subprocess.run(command, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"  FAILED {output.name}", file=sys.stderr)
        print(result.stderr.strip()[:2000], file=sys.stderr)
        return None
    return output


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--zig", help="path to the zig binary")
    parser.add_argument("--only", help="build only sources whose stem contains this")
    parser.add_argument("--out", type=Path, default=BUILD, help="output directory")
    args = parser.parse_args(argv)

    zig = find_zig(args.zig)
    version = subprocess.run([zig, "version"], capture_output=True, text=True).stdout.strip()

    args.out.mkdir(parents=True, exist_ok=True)
    write_headers(args.out)

    sources = sorted(p for p in SRC.glob("*.c") if not args.only or args.only in p.stem)
    if not sources:
        raise SystemExit(f"no sources matched --only {args.only!r}")

    print(f"zig {version} -> {args.out}")
    built = 0
    failed = 0
    for source in sources:
        for arch in TARGETS:
            for opt in OPT_LEVELS:
                if compile_one(zig, source, arch, opt, args.out) is None:
                    failed += 1
                else:
                    built += 1
        print(f"  {source.stem}")

    print(f"\n{built} binaries built, {failed} failed")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
