/* A raw 32-byte symmetric key baked into .rdata. No banner, no structure.
 *
 * The fair test for the entropy heuristic (FR-8): this is the thing it claims
 * to find, with none of the DER or PEM scaffolding the structural markers rely
 * on. If the heuristic cannot find this its recall is zero, and if it finds
 * this and a hundred other things its precision is what matters. The corpus
 * should be able to say which.
 *
 * The key is generated by corpus/build.py from the corpus seed, not chosen. The
 * threshold is 30 distinct bytes out of 32 and a random key lands right about
 * there, so picking the bytes by hand would decide the answer in advance.
 *
 * Padded either side so the key does not share a window with the ordinary data
 * around it. Ground truth: related-crypto-material. */
#include "_sink.h"
#include "raw_key.h"

static const unsigned char padding_before[64] = {0};
static const unsigned char padding_after[64] = {0};

int main(int argc, char **argv) {
    (void)argv;
    sink(padding_before, sizeof padding_before);
    sink(CORPUS_RAW_KEY + (unsigned)(argc > 99), sizeof CORPUS_RAW_KEY - 1);
    sink(padding_after, sizeof padding_after);
    return 0;
}
