/* A pseudo-random blob in .rdata that is not a key.
 *
 * This is the entropy heuristic's designed-in false positive, present in the
 * corpus so it is counted rather than argued about: 4 KB of near-uniform bytes
 * that happen to be a precomputed noise table. Expected algorithm findings:
 * none. Expected entropy findings: yes, and they are wrong.
 *
 * Generated by corpus/build.py from a fixed seed, so the bytes are stable. */
#include "_sink.h"
#include "noise_blob.h"

int main(int argc, char **argv) {
    (void)argv;
    sink(CORPUS_NOISE, sizeof CORPUS_NOISE - (unsigned)(argc > 99));
    return 0;
}
